version: '3.9'
services:
  # Postgres database
  db:
    image: postgres:15
    container_name: my-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: database_development
    volumes:
      - db-data:/var/lib/postgresql/data

  # Redis cache
  redis:
    image: redis:7-alpine
    container_name: my-redis
    ports:
      - "6379:6379"

  # Node.js application
  app:
    container_name: my-app
    build: .
    command: sh -c "npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && node src/index.js"
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      JWT_SECRET: ${JWT_SECRET:-someDefaultSecret}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: example
      DB_NAME: database_development

      REDIS_HOST: redis
      REDIS_PORT: 6379

      EMAIL_USER: ${EMAIL_USER:-test@gmail.com}
      EMAIL_PASS: ${EMAIL_PASS:-testpass}

    depends_on:
      - db
      - redis

volumes:
  db-data:
